"""setup-replication-full

Revision ID: 0551aa5b3d38
Revises: 56e62d2a6e61
Create Date: 2025-03-06 09:05:11.857942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0551aa5b3d38'
down_revision: Union[str, None] = '56e62d2a6e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE company REPLICA IDENTITY FULL"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
